Started GET "/users/auth/github" for 127.0.0.1 at 2017-10-05 21:48:51 -0400
I, [2017-10-05T21:48:51.431916 #13217]  INFO -- omniauth: (github) Request phase initiated.
Started GET "/users/auth/github" for 127.0.0.1 at 2017-10-05 21:48:51 -0400
I, [2017-10-05T21:48:51.680453 #13217]  INFO -- omniauth: (github) Request phase initiated.
Started GET "/users/auth/github/callback?code=e122522fbfb1f0ebcc8a" for 127.0.0.1 at 2017-10-05 21:48:51 -0400
I, [2017-10-05T21:48:51.939199 #13217]  INFO -- omniauth: (github) Callback phase initiated.
E, [2017-10-05T21:48:52.311079 #13217] ERROR -- omniauth: (github) Authentication failure! invalid_credentials: OAuth2::Error, incorrect_client_credentials: The client_id and/or client_secret passed are incorrect.
error=incorrect_client_credentials&error_description=The+client_id+and%2For+client_secret+passed+are+incorrect.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23incorrect-client-credentials
Processing by Devise::OmniauthCallbacksController#failure as HTML
  Parameters: {"code"=>"e122522fbfb1f0ebcc8a"}
